const orderActionTypes = {
    ADD_ORDER_TO_FIREBASE_START:'ADD_ORDER_TO_FIREBASE_START',
    ADD_ORDER_TO_FIREBASE_SUCCESS:'ADD_ORDER_TO_FIREBASE_SUCCESS',
    ADD_ORDER_TO_FIREBASE_FAILURE:'ADD_ORDER_TO_FIREBASE_FAILURE',
    FETCH_ORDER_START:'FETCH_ORDER_START',
    FETCH_ORDER_SUCCESS:'FETCH_ORDER_SUCCESS',
    FETCH_ORDER_FAILURE:'FETCH_ORDER_FAILURE',
}

export default orderActionTypes;